In [1]:
!pip install pandas scikit-learn nltk joblib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import zipfile
import pandas as pd

with zipfile.ZipFile("train.tsv.zip", "r") as zip_ref:
    zip_ref.extractall()

df = pd.read_csv(
    "train.tsv",
    sep="\t",
    encoding="latin1"
)

print(df.shape)
df.head()

(17207, 5)

,Id,EssaySet,Score1,Score2,EssayText
0,1,1,1,1,Some additional information that we would need...
1,2,1,1,1,"After reading the expirement, I realized that ..."
2,3,1,1,1,"What you need is more trials, a control set up..."
3,4,1,0,0,The student should list what rock is better an...
4,5,1,2,2,For the students to be able to make a replicat...

In [3]:
df.isnull().sum()

Id           0
EssaySet     0
Score1       0
Score2       0
EssayText    0
dtype: int64

In [4]:
print(df['Score1'].value_counts().sort_index())

Score1
0    6779
1    5612
2    4075
3     741
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Id           0
EssaySet     0
Score1       0
Score2       0
EssayText    0
dtype: int64

In [6]:
df['EssaySet'].value_counts().sort_index()

EssaySet
1     1672
2     1278
3     1891
4     1738
5     1795
6     1797
7     1799
8     1799
9     1798
10    1640
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
X = df['EssayText']
y = df['Score1']

In [9]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words='english'
)

X_vec = vectorizer.fit_transform(X)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vec,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=2000
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [12]:
from sklearn.metrics import accuracy_score

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6612434631028472

In [13]:
import joblib

joblib.dump(model, "assignment_evaluator.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("Saved Successfully")

Saved Successfully

In [14]:
sample_answer = """
Plants need sunlight because sunlight helps them make food through photosynthesis.
Without sunlight the plant cannot produce enough energy to survive.
"""

sample_vec = vectorizer.transform([sample_answer])

prediction = model.predict(sample_vec)

print("Predicted Score:", prediction[0])

Predicted Score: 0

In [15]:
print(df.iloc[100]["EssayText"])
print("Actual Score:", df.iloc[100]["Score1"])

Additional information I would need to replicate this experiment would be the actual names of the samples. In step 2 I would need the exact amount of vinegar to pour into each container. Also in step 4 I would need the amount of distilled water to rinse it off with and for how long.
Actual Score: 3

In [16]:
sample_answer = df.iloc[100]["EssayText"]

sample_vec = vectorizer.transform([sample_answer])

prediction = model.predict(sample_vec)

print("Predicted:", prediction[0])
print("Actual:", df.iloc[100]["Score1"])

Predicted: 2
Actual: 3

In [17]:
sample_answer = df.iloc[100]["EssayText"]

sample_vec = vectorizer.transform([sample_answer])

prediction = model.predict(sample_vec)

print("Predicted:", prediction[0])
print("Actual:", df.iloc[100]["Score1"])

Predicted: 2
Actual: 3

In [18]:
df["combined_text"] = (
    "EssaySet_" +
    df["EssaySet"].astype(str) +
    " " +
    df["EssayText"]
)

In [19]:
X = df["combined_text"]
y = df["Score1"]

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer2 = TfidfVectorizer(
    max_features=15000,
    stop_words="english"
)

X_vec = vectorizer2.fit_transform(X)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vec,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
from sklearn.linear_model import LogisticRegression

model2 = LogisticRegression(
    max_iter=3000
)

model2.fit(X_train, y_train)

LogisticRegression(max_iter=3000)

In [23]:
from sklearn.metrics import accuracy_score

preds2 = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds2))

Accuracy: 0.6673445671121441

In [24]:
import joblib

joblib.dump(model2, "assignment_evaluator.pkl")
joblib.dump(vectorizer2, "vectorizer.pkl")

['vectorizer.pkl']